language: node_js

node_js:
  - '6'
  - '8'

cache: yarn

deploy:
  provider: npm
  email: hello@originate.com
  api_key:
    secure: AN3CPKLvttsr6v6WQ3fFxGuW9Dbw74mJBrO9TRaQl6Ae+pkaVKNIqmPLCoohzUq77oYSmM+rJxkbReVm78mW04AZHAhRguN8vDDCK/2fX//A5R1joxA19bCp9klocVoZRA65p196EOm0eyRC4Ij4XnmTKl0mKY2pNbDxmVEG3m+2rOf07SDGufA1gZ8F2i3Ii2bpiLPrF5PX1Xhh0tUeO4cGGG1TbleKKKT7QaxDh/ToVykRLaEsh6OhkSSTgcWZctUph2n4wURSrx5/D/s8W0/28Dl3IE9XVrpKiut1nXLnZFehcC+WN40+CETVm5xv610MkQtxgFRYlYgHtmDDEvKxNUjZxQEQnqnzbAGHnWrJ5oY8I34dPHs9L76zM7lRE5yuJz9khs1SQ2IMcdj5icX3nmQOl4Sd70Gpins0u9x+HptrqKCzGjlJYMfp8/5Xs3Eje61uJ2qDz5qCA6qrwpM0kYywtx6lByXuQ1BApD66o6BHw0xdG+PdCfox2649BeUE7Tk9inG8WGKgdO+b3M0h8Rb1iL5MXJfyFDst5x1XPKP5zgHY7DDHpSrLrmctyB4von5WO/RFDI5z10ZtCia34cxMTqGOdItPc1pd6fPCeldZKFa/H74ngAqCvmrUt64LxhU8S/ZIpZevetFQ2MDrdJkh7Hbav65Hpo5rtI0=
  on:
    tags: true
    node: '6'
    repo: Originate/text-runner

notifications:
  email: false
